resolve-type-alias:     false
issue-845-fix:          true
disable-version-string: true
with-expecter:          true
dir:                    "{{.ConfigDir}}/internal/xmock/{{.PackageName}}mock"
outpkg:                 "{{.PackageName}}mock"
mockname:               "{{.InterfaceName|camelcase}}"
filename:               "{{.InterfaceName|lower}}.go"
packages:
  github.com/nats-io/nats.go/jetstream:
    interfaces:
      Consumer:
      KeyValue:
      KeyValueEntry:
      KeyWatcher:
  github.com/mikluko/peanats:
    interfaces:
      Connection:
      Msg:
      MsgJetstream:
  github.com/mikluko/peanats/bucket:
    interfaces:
      Entry:
      Watcher:
