dir: "{{.ConfigDir}}/internal/xmock/{{.SrcPackageName}}mock"
filename: "{{.InterfaceName|lower}}.go"
pkgname: "{{.SrcPackageName}}mock"
structname: "{{.InterfaceName}}"
packages:
  github.com/nats-io/nats.go/jetstream:
    interfaces:
      Consumer:
      KeyValue:
      KeyValueEntry:
      KeyWatcher:
  github.com/mikluko/peanats:
    interfaces:
      Connection:
      Msg:
      MsgJetstream:
  github.com/mikluko/peanats/bucket:
    interfaces:
      Entry:
      Watcher:
  github.com/mikluko/peanats/requester:
    interfaces:
      Requester:
      Response:
      ResponseReceiver:
