resolve-type-alias:     false
issue-845-fix:          true
disable-version-string: true
with-expecter:          true
dir:                    "{{.ConfigDir}}"
outpkg:                 "peanats_test"
mockname:               "{{.InterfaceName|camelcase|firstLower}}Mock"
filename:               "xmock_{{.InterfaceName|lower}}_test.go"
packages:
  github.com/nats-io/nats.go/jetstream:
    interfaces:
      Consumer:
      KeyValue:
      KeyValueEntry:
      KeyWatcher:
  github.com/mikluko/peanats:
    interfaces:
      Message:
      BucketEntry:
      BucketWatcher:
      natsRequester:
