// Code generated by mockery. DO NOT EDIT.

package peanats_test

import (
	peanats "github.com/mikluko/peanats"
	mock "github.com/stretchr/testify/mock"
)

// bucketWatcherMock is an autogenerated mock type for the BucketWatcher type
type bucketWatcherMock[T any] struct {
	mock.Mock
}

type bucketWatcherMock_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *bucketWatcherMock[T]) EXPECT() *bucketWatcherMock_Expecter[T] {
	return &bucketWatcherMock_Expecter[T]{mock: &_m.Mock}
}

// Next provides a mock function with no fields
func (_m *bucketWatcherMock[T]) Next() (peanats.BucketEntry[T], error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 peanats.BucketEntry[T]
	var r1 error
	if rf, ok := ret.Get(0).(func() (peanats.BucketEntry[T], error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() peanats.BucketEntry[T]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peanats.BucketEntry[T])
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bucketWatcherMock_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type bucketWatcherMock_Next_Call[T any] struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *bucketWatcherMock_Expecter[T]) Next() *bucketWatcherMock_Next_Call[T] {
	return &bucketWatcherMock_Next_Call[T]{Call: _e.mock.On("Next")}
}

func (_c *bucketWatcherMock_Next_Call[T]) Run(run func()) *bucketWatcherMock_Next_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *bucketWatcherMock_Next_Call[T]) Return(_a0 peanats.BucketEntry[T], _a1 error) *bucketWatcherMock_Next_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bucketWatcherMock_Next_Call[T]) RunAndReturn(run func() (peanats.BucketEntry[T], error)) *bucketWatcherMock_Next_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *bucketWatcherMock[T]) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// bucketWatcherMock_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type bucketWatcherMock_Stop_Call[T any] struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *bucketWatcherMock_Expecter[T]) Stop() *bucketWatcherMock_Stop_Call[T] {
	return &bucketWatcherMock_Stop_Call[T]{Call: _e.mock.On("Stop")}
}

func (_c *bucketWatcherMock_Stop_Call[T]) Run(run func()) *bucketWatcherMock_Stop_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *bucketWatcherMock_Stop_Call[T]) Return(_a0 error) *bucketWatcherMock_Stop_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bucketWatcherMock_Stop_Call[T]) RunAndReturn(run func() error) *bucketWatcherMock_Stop_Call[T] {
	_c.Call.Return(run)
	return _c
}

// newBucketWatcherMock creates a new instance of bucketWatcherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newBucketWatcherMock[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *bucketWatcherMock[T] {
	mock := &bucketWatcherMock[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
