// Code generated by mockery. DO NOT EDIT.

package peanats_test

import (
	jetstream "github.com/nats-io/nats.go/jetstream"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// keyValueEntryMock is an autogenerated mock type for the KeyValueEntry type
type keyValueEntryMock struct {
	mock.Mock
}

type keyValueEntryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *keyValueEntryMock) EXPECT() *keyValueEntryMock_Expecter {
	return &keyValueEntryMock_Expecter{mock: &_m.Mock}
}

// Bucket provides a mock function with no fields
func (_m *keyValueEntryMock) Bucket() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Bucket")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// keyValueEntryMock_Bucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bucket'
type keyValueEntryMock_Bucket_Call struct {
	*mock.Call
}

// Bucket is a helper method to define mock.On call
func (_e *keyValueEntryMock_Expecter) Bucket() *keyValueEntryMock_Bucket_Call {
	return &keyValueEntryMock_Bucket_Call{Call: _e.mock.On("Bucket")}
}

func (_c *keyValueEntryMock_Bucket_Call) Run(run func()) *keyValueEntryMock_Bucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *keyValueEntryMock_Bucket_Call) Return(_a0 string) *keyValueEntryMock_Bucket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *keyValueEntryMock_Bucket_Call) RunAndReturn(run func() string) *keyValueEntryMock_Bucket_Call {
	_c.Call.Return(run)
	return _c
}

// Created provides a mock function with no fields
func (_m *keyValueEntryMock) Created() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Created")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// keyValueEntryMock_Created_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Created'
type keyValueEntryMock_Created_Call struct {
	*mock.Call
}

// Created is a helper method to define mock.On call
func (_e *keyValueEntryMock_Expecter) Created() *keyValueEntryMock_Created_Call {
	return &keyValueEntryMock_Created_Call{Call: _e.mock.On("Created")}
}

func (_c *keyValueEntryMock_Created_Call) Run(run func()) *keyValueEntryMock_Created_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *keyValueEntryMock_Created_Call) Return(_a0 time.Time) *keyValueEntryMock_Created_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *keyValueEntryMock_Created_Call) RunAndReturn(run func() time.Time) *keyValueEntryMock_Created_Call {
	_c.Call.Return(run)
	return _c
}

// Delta provides a mock function with no fields
func (_m *keyValueEntryMock) Delta() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Delta")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// keyValueEntryMock_Delta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delta'
type keyValueEntryMock_Delta_Call struct {
	*mock.Call
}

// Delta is a helper method to define mock.On call
func (_e *keyValueEntryMock_Expecter) Delta() *keyValueEntryMock_Delta_Call {
	return &keyValueEntryMock_Delta_Call{Call: _e.mock.On("Delta")}
}

func (_c *keyValueEntryMock_Delta_Call) Run(run func()) *keyValueEntryMock_Delta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *keyValueEntryMock_Delta_Call) Return(_a0 uint64) *keyValueEntryMock_Delta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *keyValueEntryMock_Delta_Call) RunAndReturn(run func() uint64) *keyValueEntryMock_Delta_Call {
	_c.Call.Return(run)
	return _c
}

// Key provides a mock function with no fields
func (_m *keyValueEntryMock) Key() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Key")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// keyValueEntryMock_Key_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Key'
type keyValueEntryMock_Key_Call struct {
	*mock.Call
}

// Key is a helper method to define mock.On call
func (_e *keyValueEntryMock_Expecter) Key() *keyValueEntryMock_Key_Call {
	return &keyValueEntryMock_Key_Call{Call: _e.mock.On("Key")}
}

func (_c *keyValueEntryMock_Key_Call) Run(run func()) *keyValueEntryMock_Key_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *keyValueEntryMock_Key_Call) Return(_a0 string) *keyValueEntryMock_Key_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *keyValueEntryMock_Key_Call) RunAndReturn(run func() string) *keyValueEntryMock_Key_Call {
	_c.Call.Return(run)
	return _c
}

// Operation provides a mock function with no fields
func (_m *keyValueEntryMock) Operation() jetstream.KeyValueOp {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operation")
	}

	var r0 jetstream.KeyValueOp
	if rf, ok := ret.Get(0).(func() jetstream.KeyValueOp); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(jetstream.KeyValueOp)
	}

	return r0
}

// keyValueEntryMock_Operation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operation'
type keyValueEntryMock_Operation_Call struct {
	*mock.Call
}

// Operation is a helper method to define mock.On call
func (_e *keyValueEntryMock_Expecter) Operation() *keyValueEntryMock_Operation_Call {
	return &keyValueEntryMock_Operation_Call{Call: _e.mock.On("Operation")}
}

func (_c *keyValueEntryMock_Operation_Call) Run(run func()) *keyValueEntryMock_Operation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *keyValueEntryMock_Operation_Call) Return(_a0 jetstream.KeyValueOp) *keyValueEntryMock_Operation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *keyValueEntryMock_Operation_Call) RunAndReturn(run func() jetstream.KeyValueOp) *keyValueEntryMock_Operation_Call {
	_c.Call.Return(run)
	return _c
}

// Revision provides a mock function with no fields
func (_m *keyValueEntryMock) Revision() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Revision")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// keyValueEntryMock_Revision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revision'
type keyValueEntryMock_Revision_Call struct {
	*mock.Call
}

// Revision is a helper method to define mock.On call
func (_e *keyValueEntryMock_Expecter) Revision() *keyValueEntryMock_Revision_Call {
	return &keyValueEntryMock_Revision_Call{Call: _e.mock.On("Revision")}
}

func (_c *keyValueEntryMock_Revision_Call) Run(run func()) *keyValueEntryMock_Revision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *keyValueEntryMock_Revision_Call) Return(_a0 uint64) *keyValueEntryMock_Revision_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *keyValueEntryMock_Revision_Call) RunAndReturn(run func() uint64) *keyValueEntryMock_Revision_Call {
	_c.Call.Return(run)
	return _c
}

// Value provides a mock function with no fields
func (_m *keyValueEntryMock) Value() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// keyValueEntryMock_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type keyValueEntryMock_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
func (_e *keyValueEntryMock_Expecter) Value() *keyValueEntryMock_Value_Call {
	return &keyValueEntryMock_Value_Call{Call: _e.mock.On("Value")}
}

func (_c *keyValueEntryMock_Value_Call) Run(run func()) *keyValueEntryMock_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *keyValueEntryMock_Value_Call) Return(_a0 []byte) *keyValueEntryMock_Value_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *keyValueEntryMock_Value_Call) RunAndReturn(run func() []byte) *keyValueEntryMock_Value_Call {
	_c.Call.Return(run)
	return _c
}

// newKeyValueEntryMock creates a new instance of keyValueEntryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newKeyValueEntryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *keyValueEntryMock {
	mock := &keyValueEntryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
