// Code generated by mockery. DO NOT EDIT.

package peanats_test

import (
	jetstream "github.com/nats-io/nats.go/jetstream"
	mock "github.com/stretchr/testify/mock"

	textproto "net/textproto"

	time "time"
)

// bucketEntryMock is an autogenerated mock type for the BucketEntry type
type bucketEntryMock[T any] struct {
	mock.Mock
}

type bucketEntryMock_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *bucketEntryMock[T]) EXPECT() *bucketEntryMock_Expecter[T] {
	return &bucketEntryMock_Expecter[T]{mock: &_m.Mock}
}

// Bucket provides a mock function with no fields
func (_m *bucketEntryMock[T]) Bucket() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Bucket")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// bucketEntryMock_Bucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bucket'
type bucketEntryMock_Bucket_Call[T any] struct {
	*mock.Call
}

// Bucket is a helper method to define mock.On call
func (_e *bucketEntryMock_Expecter[T]) Bucket() *bucketEntryMock_Bucket_Call[T] {
	return &bucketEntryMock_Bucket_Call[T]{Call: _e.mock.On("Bucket")}
}

func (_c *bucketEntryMock_Bucket_Call[T]) Run(run func()) *bucketEntryMock_Bucket_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *bucketEntryMock_Bucket_Call[T]) Return(_a0 string) *bucketEntryMock_Bucket_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bucketEntryMock_Bucket_Call[T]) RunAndReturn(run func() string) *bucketEntryMock_Bucket_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Created provides a mock function with no fields
func (_m *bucketEntryMock[T]) Created() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Created")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// bucketEntryMock_Created_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Created'
type bucketEntryMock_Created_Call[T any] struct {
	*mock.Call
}

// Created is a helper method to define mock.On call
func (_e *bucketEntryMock_Expecter[T]) Created() *bucketEntryMock_Created_Call[T] {
	return &bucketEntryMock_Created_Call[T]{Call: _e.mock.On("Created")}
}

func (_c *bucketEntryMock_Created_Call[T]) Run(run func()) *bucketEntryMock_Created_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *bucketEntryMock_Created_Call[T]) Return(_a0 time.Time) *bucketEntryMock_Created_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bucketEntryMock_Created_Call[T]) RunAndReturn(run func() time.Time) *bucketEntryMock_Created_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Delta provides a mock function with no fields
func (_m *bucketEntryMock[T]) Delta() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Delta")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// bucketEntryMock_Delta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delta'
type bucketEntryMock_Delta_Call[T any] struct {
	*mock.Call
}

// Delta is a helper method to define mock.On call
func (_e *bucketEntryMock_Expecter[T]) Delta() *bucketEntryMock_Delta_Call[T] {
	return &bucketEntryMock_Delta_Call[T]{Call: _e.mock.On("Delta")}
}

func (_c *bucketEntryMock_Delta_Call[T]) Run(run func()) *bucketEntryMock_Delta_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *bucketEntryMock_Delta_Call[T]) Return(_a0 uint64) *bucketEntryMock_Delta_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bucketEntryMock_Delta_Call[T]) RunAndReturn(run func() uint64) *bucketEntryMock_Delta_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with no fields
func (_m *bucketEntryMock[T]) Header() textproto.MIMEHeader {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 textproto.MIMEHeader
	if rf, ok := ret.Get(0).(func() textproto.MIMEHeader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(textproto.MIMEHeader)
		}
	}

	return r0
}

// bucketEntryMock_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type bucketEntryMock_Header_Call[T any] struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *bucketEntryMock_Expecter[T]) Header() *bucketEntryMock_Header_Call[T] {
	return &bucketEntryMock_Header_Call[T]{Call: _e.mock.On("Header")}
}

func (_c *bucketEntryMock_Header_Call[T]) Run(run func()) *bucketEntryMock_Header_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *bucketEntryMock_Header_Call[T]) Return(_a0 textproto.MIMEHeader) *bucketEntryMock_Header_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bucketEntryMock_Header_Call[T]) RunAndReturn(run func() textproto.MIMEHeader) *bucketEntryMock_Header_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Key provides a mock function with no fields
func (_m *bucketEntryMock[T]) Key() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Key")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// bucketEntryMock_Key_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Key'
type bucketEntryMock_Key_Call[T any] struct {
	*mock.Call
}

// Key is a helper method to define mock.On call
func (_e *bucketEntryMock_Expecter[T]) Key() *bucketEntryMock_Key_Call[T] {
	return &bucketEntryMock_Key_Call[T]{Call: _e.mock.On("Key")}
}

func (_c *bucketEntryMock_Key_Call[T]) Run(run func()) *bucketEntryMock_Key_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *bucketEntryMock_Key_Call[T]) Return(_a0 string) *bucketEntryMock_Key_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bucketEntryMock_Key_Call[T]) RunAndReturn(run func() string) *bucketEntryMock_Key_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Operation provides a mock function with no fields
func (_m *bucketEntryMock[T]) Operation() jetstream.KeyValueOp {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operation")
	}

	var r0 jetstream.KeyValueOp
	if rf, ok := ret.Get(0).(func() jetstream.KeyValueOp); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(jetstream.KeyValueOp)
	}

	return r0
}

// bucketEntryMock_Operation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operation'
type bucketEntryMock_Operation_Call[T any] struct {
	*mock.Call
}

// Operation is a helper method to define mock.On call
func (_e *bucketEntryMock_Expecter[T]) Operation() *bucketEntryMock_Operation_Call[T] {
	return &bucketEntryMock_Operation_Call[T]{Call: _e.mock.On("Operation")}
}

func (_c *bucketEntryMock_Operation_Call[T]) Run(run func()) *bucketEntryMock_Operation_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *bucketEntryMock_Operation_Call[T]) Return(_a0 jetstream.KeyValueOp) *bucketEntryMock_Operation_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bucketEntryMock_Operation_Call[T]) RunAndReturn(run func() jetstream.KeyValueOp) *bucketEntryMock_Operation_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Revision provides a mock function with no fields
func (_m *bucketEntryMock[T]) Revision() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Revision")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// bucketEntryMock_Revision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revision'
type bucketEntryMock_Revision_Call[T any] struct {
	*mock.Call
}

// Revision is a helper method to define mock.On call
func (_e *bucketEntryMock_Expecter[T]) Revision() *bucketEntryMock_Revision_Call[T] {
	return &bucketEntryMock_Revision_Call[T]{Call: _e.mock.On("Revision")}
}

func (_c *bucketEntryMock_Revision_Call[T]) Run(run func()) *bucketEntryMock_Revision_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *bucketEntryMock_Revision_Call[T]) Return(_a0 uint64) *bucketEntryMock_Revision_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bucketEntryMock_Revision_Call[T]) RunAndReturn(run func() uint64) *bucketEntryMock_Revision_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Value provides a mock function with no fields
func (_m *bucketEntryMock[T]) Value() *T {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 *T
	if rf, ok := ret.Get(0).(func() *T); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}

	return r0
}

// bucketEntryMock_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type bucketEntryMock_Value_Call[T any] struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
func (_e *bucketEntryMock_Expecter[T]) Value() *bucketEntryMock_Value_Call[T] {
	return &bucketEntryMock_Value_Call[T]{Call: _e.mock.On("Value")}
}

func (_c *bucketEntryMock_Value_Call[T]) Run(run func()) *bucketEntryMock_Value_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *bucketEntryMock_Value_Call[T]) Return(_a0 *T) *bucketEntryMock_Value_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bucketEntryMock_Value_Call[T]) RunAndReturn(run func() *T) *bucketEntryMock_Value_Call[T] {
	_c.Call.Return(run)
	return _c
}

// newBucketEntryMock creates a new instance of bucketEntryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newBucketEntryMock[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *bucketEntryMock[T] {
	mock := &bucketEntryMock[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
