// Code generated by mockery. DO NOT EDIT.

package peanatsmock

import (
	context "context"

	peanats "github.com/mikluko/peanats"
	mock "github.com/stretchr/testify/mock"
)

// Connection is an autogenerated mock type for the Connection type
type Connection struct {
	mock.Mock
}

type Connection_Expecter struct {
	mock *mock.Mock
}

func (_m *Connection) EXPECT() *Connection_Expecter {
	return &Connection_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Connection) Close() {
	_m.Called()
}

// Connection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Connection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Connection_Expecter) Close() *Connection_Close_Call {
	return &Connection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Connection_Close_Call) Run(run func()) *Connection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connection_Close_Call) Return() *Connection_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *Connection_Close_Call) RunAndReturn(run func()) *Connection_Close_Call {
	_c.Run(run)
	return _c
}

// Drain provides a mock function with no fields
func (_m *Connection) Drain() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Drain")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connection_Drain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drain'
type Connection_Drain_Call struct {
	*mock.Call
}

// Drain is a helper method to define mock.On call
func (_e *Connection_Expecter) Drain() *Connection_Drain_Call {
	return &Connection_Drain_Call{Call: _e.mock.On("Drain")}
}

func (_c *Connection_Drain_Call) Run(run func()) *Connection_Drain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connection_Drain_Call) Return(_a0 error) *Connection_Drain_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connection_Drain_Call) RunAndReturn(run func() error) *Connection_Drain_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, msg
func (_m *Connection) Publish(ctx context.Context, msg peanats.Msg) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, peanats.Msg) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connection_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Connection_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - msg peanats.Msg
func (_e *Connection_Expecter) Publish(ctx interface{}, msg interface{}) *Connection_Publish_Call {
	return &Connection_Publish_Call{Call: _e.mock.On("Publish", ctx, msg)}
}

func (_c *Connection_Publish_Call) Run(run func(ctx context.Context, msg peanats.Msg)) *Connection_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(peanats.Msg))
	})
	return _c
}

func (_c *Connection_Publish_Call) Return(_a0 error) *Connection_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connection_Publish_Call) RunAndReturn(run func(context.Context, peanats.Msg) error) *Connection_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function with given fields: ctx, msg
func (_m *Connection) Request(ctx context.Context, msg peanats.Msg) (peanats.Msg, error) {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 peanats.Msg
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, peanats.Msg) (peanats.Msg, error)); ok {
		return rf(ctx, msg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, peanats.Msg) peanats.Msg); ok {
		r0 = rf(ctx, msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peanats.Msg)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, peanats.Msg) error); ok {
		r1 = rf(ctx, msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connection_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type Connection_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - ctx context.Context
//   - msg peanats.Msg
func (_e *Connection_Expecter) Request(ctx interface{}, msg interface{}) *Connection_Request_Call {
	return &Connection_Request_Call{Call: _e.mock.On("Request", ctx, msg)}
}

func (_c *Connection_Request_Call) Run(run func(ctx context.Context, msg peanats.Msg)) *Connection_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(peanats.Msg))
	})
	return _c
}

func (_c *Connection_Request_Call) Return(_a0 peanats.Msg, _a1 error) *Connection_Request_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connection_Request_Call) RunAndReturn(run func(context.Context, peanats.Msg) (peanats.Msg, error)) *Connection_Request_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, subj, opts
func (_m *Connection) Subscribe(ctx context.Context, subj string, opts ...peanats.SubscribeOption) (peanats.Subscription, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, subj)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 peanats.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...peanats.SubscribeOption) (peanats.Subscription, error)); ok {
		return rf(ctx, subj, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...peanats.SubscribeOption) peanats.Subscription); ok {
		r0 = rf(ctx, subj, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peanats.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...peanats.SubscribeOption) error); ok {
		r1 = rf(ctx, subj, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connection_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type Connection_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - subj string
//   - opts ...peanats.SubscribeOption
func (_e *Connection_Expecter) Subscribe(ctx interface{}, subj interface{}, opts ...interface{}) *Connection_Subscribe_Call {
	return &Connection_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{ctx, subj}, opts...)...)}
}

func (_c *Connection_Subscribe_Call) Run(run func(ctx context.Context, subj string, opts ...peanats.SubscribeOption)) *Connection_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]peanats.SubscribeOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(peanats.SubscribeOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *Connection_Subscribe_Call) Return(_a0 peanats.Subscription, _a1 error) *Connection_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connection_Subscribe_Call) RunAndReturn(run func(context.Context, string, ...peanats.SubscribeOption) (peanats.Subscription, error)) *Connection_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeChan provides a mock function with given fields: ctx, subj, ch, opts
func (_m *Connection) SubscribeChan(ctx context.Context, subj string, ch chan peanats.Msg, opts ...peanats.SubscribeChanOption) (peanats.Unsubscriber, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, subj, ch)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeChan")
	}

	var r0 peanats.Unsubscriber
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, chan peanats.Msg, ...peanats.SubscribeChanOption) (peanats.Unsubscriber, error)); ok {
		return rf(ctx, subj, ch, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, chan peanats.Msg, ...peanats.SubscribeChanOption) peanats.Unsubscriber); ok {
		r0 = rf(ctx, subj, ch, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peanats.Unsubscriber)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, chan peanats.Msg, ...peanats.SubscribeChanOption) error); ok {
		r1 = rf(ctx, subj, ch, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connection_SubscribeChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeChan'
type Connection_SubscribeChan_Call struct {
	*mock.Call
}

// SubscribeChan is a helper method to define mock.On call
//   - ctx context.Context
//   - subj string
//   - ch chan peanats.Msg
//   - opts ...peanats.SubscribeChanOption
func (_e *Connection_Expecter) SubscribeChan(ctx interface{}, subj interface{}, ch interface{}, opts ...interface{}) *Connection_SubscribeChan_Call {
	return &Connection_SubscribeChan_Call{Call: _e.mock.On("SubscribeChan",
		append([]interface{}{ctx, subj, ch}, opts...)...)}
}

func (_c *Connection_SubscribeChan_Call) Run(run func(ctx context.Context, subj string, ch chan peanats.Msg, opts ...peanats.SubscribeChanOption)) *Connection_SubscribeChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]peanats.SubscribeChanOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(peanats.SubscribeChanOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(chan peanats.Msg), variadicArgs...)
	})
	return _c
}

func (_c *Connection_SubscribeChan_Call) Return(_a0 peanats.Unsubscriber, _a1 error) *Connection_SubscribeChan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connection_SubscribeChan_Call) RunAndReturn(run func(context.Context, string, chan peanats.Msg, ...peanats.SubscribeChanOption) (peanats.Unsubscriber, error)) *Connection_SubscribeChan_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeHandler provides a mock function with given fields: ctx, subj, handler, opts
func (_m *Connection) SubscribeHandler(ctx context.Context, subj string, handler peanats.MsgHandler, opts ...peanats.SubscribeHandlerOption) (peanats.Unsubscriber, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, subj, handler)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeHandler")
	}

	var r0 peanats.Unsubscriber
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, peanats.MsgHandler, ...peanats.SubscribeHandlerOption) (peanats.Unsubscriber, error)); ok {
		return rf(ctx, subj, handler, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, peanats.MsgHandler, ...peanats.SubscribeHandlerOption) peanats.Unsubscriber); ok {
		r0 = rf(ctx, subj, handler, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peanats.Unsubscriber)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, peanats.MsgHandler, ...peanats.SubscribeHandlerOption) error); ok {
		r1 = rf(ctx, subj, handler, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connection_SubscribeHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeHandler'
type Connection_SubscribeHandler_Call struct {
	*mock.Call
}

// SubscribeHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - subj string
//   - handler peanats.MsgHandler
//   - opts ...peanats.SubscribeHandlerOption
func (_e *Connection_Expecter) SubscribeHandler(ctx interface{}, subj interface{}, handler interface{}, opts ...interface{}) *Connection_SubscribeHandler_Call {
	return &Connection_SubscribeHandler_Call{Call: _e.mock.On("SubscribeHandler",
		append([]interface{}{ctx, subj, handler}, opts...)...)}
}

func (_c *Connection_SubscribeHandler_Call) Run(run func(ctx context.Context, subj string, handler peanats.MsgHandler, opts ...peanats.SubscribeHandlerOption)) *Connection_SubscribeHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]peanats.SubscribeHandlerOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(peanats.SubscribeHandlerOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(peanats.MsgHandler), variadicArgs...)
	})
	return _c
}

func (_c *Connection_SubscribeHandler_Call) Return(_a0 peanats.Unsubscriber, _a1 error) *Connection_SubscribeHandler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connection_SubscribeHandler_Call) RunAndReturn(run func(context.Context, string, peanats.MsgHandler, ...peanats.SubscribeHandlerOption) (peanats.Unsubscriber, error)) *Connection_SubscribeHandler_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnection creates a new instance of Connection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *Connection {
	mock := &Connection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
