// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transportmock

import (
	"context"

	"github.com/mikluko/peanats"
	"github.com/mikluko/peanats/transport"
	mock "github.com/stretchr/testify/mock"
)

// NewConn creates a new instance of Conn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *Conn {
	mock := &Conn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Conn is an autogenerated mock type for the Conn type
type Conn struct {
	mock.Mock
}

type Conn_Expecter struct {
	mock *mock.Mock
}

func (_m *Conn) EXPECT() *Conn_Expecter {
	return &Conn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Conn
func (_mock *Conn) Close() {
	_mock.Called()
	return
}

// Conn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Conn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Conn_Expecter) Close() *Conn_Close_Call {
	return &Conn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Conn_Close_Call) Run(run func()) *Conn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Conn_Close_Call) Return() *Conn_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *Conn_Close_Call) RunAndReturn(run func()) *Conn_Close_Call {
	_c.Run(run)
	return _c
}

// Drain provides a mock function for the type Conn
func (_mock *Conn) Drain() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Drain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Conn_Drain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drain'
type Conn_Drain_Call struct {
	*mock.Call
}

// Drain is a helper method to define mock.On call
func (_e *Conn_Expecter) Drain() *Conn_Drain_Call {
	return &Conn_Drain_Call{Call: _e.mock.On("Drain")}
}

func (_c *Conn_Drain_Call) Run(run func()) *Conn_Drain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Conn_Drain_Call) Return(err error) *Conn_Drain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Conn_Drain_Call) RunAndReturn(run func() error) *Conn_Drain_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type Conn
func (_mock *Conn) Publish(ctx context.Context, msg peanats.Msg) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, peanats.Msg) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Conn_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Conn_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - msg peanats.Msg
func (_e *Conn_Expecter) Publish(ctx interface{}, msg interface{}) *Conn_Publish_Call {
	return &Conn_Publish_Call{Call: _e.mock.On("Publish", ctx, msg)}
}

func (_c *Conn_Publish_Call) Run(run func(ctx context.Context, msg peanats.Msg)) *Conn_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 peanats.Msg
		if args[1] != nil {
			arg1 = args[1].(peanats.Msg)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Conn_Publish_Call) Return(err error) *Conn_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Conn_Publish_Call) RunAndReturn(run func(ctx context.Context, msg peanats.Msg) error) *Conn_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function for the type Conn
func (_mock *Conn) Request(ctx context.Context, msg peanats.Msg) (peanats.Msg, error) {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 peanats.Msg
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, peanats.Msg) (peanats.Msg, error)); ok {
		return returnFunc(ctx, msg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, peanats.Msg) peanats.Msg); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peanats.Msg)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, peanats.Msg) error); ok {
		r1 = returnFunc(ctx, msg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Conn_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type Conn_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - ctx context.Context
//   - msg peanats.Msg
func (_e *Conn_Expecter) Request(ctx interface{}, msg interface{}) *Conn_Request_Call {
	return &Conn_Request_Call{Call: _e.mock.On("Request", ctx, msg)}
}

func (_c *Conn_Request_Call) Run(run func(ctx context.Context, msg peanats.Msg)) *Conn_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 peanats.Msg
		if args[1] != nil {
			arg1 = args[1].(peanats.Msg)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Conn_Request_Call) Return(msg1 peanats.Msg, err error) *Conn_Request_Call {
	_c.Call.Return(msg1, err)
	return _c
}

func (_c *Conn_Request_Call) RunAndReturn(run func(ctx context.Context, msg peanats.Msg) (peanats.Msg, error)) *Conn_Request_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type Conn
func (_mock *Conn) Subscribe(ctx context.Context, subj string, opts ...transport.SubscribeOption) (peanats.Subscription, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, subj, opts)
	} else {
		tmpRet = _mock.Called(ctx, subj)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 peanats.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...transport.SubscribeOption) (peanats.Subscription, error)); ok {
		return returnFunc(ctx, subj, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...transport.SubscribeOption) peanats.Subscription); ok {
		r0 = returnFunc(ctx, subj, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peanats.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...transport.SubscribeOption) error); ok {
		r1 = returnFunc(ctx, subj, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Conn_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type Conn_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - subj string
//   - opts ...transport.SubscribeOption
func (_e *Conn_Expecter) Subscribe(ctx interface{}, subj interface{}, opts ...interface{}) *Conn_Subscribe_Call {
	return &Conn_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{ctx, subj}, opts...)...)}
}

func (_c *Conn_Subscribe_Call) Run(run func(ctx context.Context, subj string, opts ...transport.SubscribeOption)) *Conn_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []transport.SubscribeOption
		var variadicArgs []transport.SubscribeOption
		if len(args) > 2 {
			variadicArgs = args[2].([]transport.SubscribeOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Conn_Subscribe_Call) Return(subscription peanats.Subscription, err error) *Conn_Subscribe_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *Conn_Subscribe_Call) RunAndReturn(run func(ctx context.Context, subj string, opts ...transport.SubscribeOption) (peanats.Subscription, error)) *Conn_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeChan provides a mock function for the type Conn
func (_mock *Conn) SubscribeChan(ctx context.Context, subj string, ch chan peanats.Msg, opts ...transport.SubscribeChanOption) (peanats.Unsubscriber, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, subj, ch, opts)
	} else {
		tmpRet = _mock.Called(ctx, subj, ch)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SubscribeChan")
	}

	var r0 peanats.Unsubscriber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, chan peanats.Msg, ...transport.SubscribeChanOption) (peanats.Unsubscriber, error)); ok {
		return returnFunc(ctx, subj, ch, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, chan peanats.Msg, ...transport.SubscribeChanOption) peanats.Unsubscriber); ok {
		r0 = returnFunc(ctx, subj, ch, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peanats.Unsubscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, chan peanats.Msg, ...transport.SubscribeChanOption) error); ok {
		r1 = returnFunc(ctx, subj, ch, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Conn_SubscribeChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeChan'
type Conn_SubscribeChan_Call struct {
	*mock.Call
}

// SubscribeChan is a helper method to define mock.On call
//   - ctx context.Context
//   - subj string
//   - ch chan peanats.Msg
//   - opts ...transport.SubscribeChanOption
func (_e *Conn_Expecter) SubscribeChan(ctx interface{}, subj interface{}, ch interface{}, opts ...interface{}) *Conn_SubscribeChan_Call {
	return &Conn_SubscribeChan_Call{Call: _e.mock.On("SubscribeChan",
		append([]interface{}{ctx, subj, ch}, opts...)...)}
}

func (_c *Conn_SubscribeChan_Call) Run(run func(ctx context.Context, subj string, ch chan peanats.Msg, opts ...transport.SubscribeChanOption)) *Conn_SubscribeChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 chan peanats.Msg
		if args[2] != nil {
			arg2 = args[2].(chan peanats.Msg)
		}
		var arg3 []transport.SubscribeChanOption
		var variadicArgs []transport.SubscribeChanOption
		if len(args) > 3 {
			variadicArgs = args[3].([]transport.SubscribeChanOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Conn_SubscribeChan_Call) Return(unsubscriber peanats.Unsubscriber, err error) *Conn_SubscribeChan_Call {
	_c.Call.Return(unsubscriber, err)
	return _c
}

func (_c *Conn_SubscribeChan_Call) RunAndReturn(run func(ctx context.Context, subj string, ch chan peanats.Msg, opts ...transport.SubscribeChanOption) (peanats.Unsubscriber, error)) *Conn_SubscribeChan_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeHandler provides a mock function for the type Conn
func (_mock *Conn) SubscribeHandler(ctx context.Context, subj string, handler peanats.MsgHandler, opts ...transport.SubscribeHandlerOption) (peanats.Unsubscriber, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, subj, handler, opts)
	} else {
		tmpRet = _mock.Called(ctx, subj, handler)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SubscribeHandler")
	}

	var r0 peanats.Unsubscriber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, peanats.MsgHandler, ...transport.SubscribeHandlerOption) (peanats.Unsubscriber, error)); ok {
		return returnFunc(ctx, subj, handler, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, peanats.MsgHandler, ...transport.SubscribeHandlerOption) peanats.Unsubscriber); ok {
		r0 = returnFunc(ctx, subj, handler, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peanats.Unsubscriber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, peanats.MsgHandler, ...transport.SubscribeHandlerOption) error); ok {
		r1 = returnFunc(ctx, subj, handler, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Conn_SubscribeHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeHandler'
type Conn_SubscribeHandler_Call struct {
	*mock.Call
}

// SubscribeHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - subj string
//   - handler peanats.MsgHandler
//   - opts ...transport.SubscribeHandlerOption
func (_e *Conn_Expecter) SubscribeHandler(ctx interface{}, subj interface{}, handler interface{}, opts ...interface{}) *Conn_SubscribeHandler_Call {
	return &Conn_SubscribeHandler_Call{Call: _e.mock.On("SubscribeHandler",
		append([]interface{}{ctx, subj, handler}, opts...)...)}
}

func (_c *Conn_SubscribeHandler_Call) Run(run func(ctx context.Context, subj string, handler peanats.MsgHandler, opts ...transport.SubscribeHandlerOption)) *Conn_SubscribeHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 peanats.MsgHandler
		if args[2] != nil {
			arg2 = args[2].(peanats.MsgHandler)
		}
		var arg3 []transport.SubscribeHandlerOption
		var variadicArgs []transport.SubscribeHandlerOption
		if len(args) > 3 {
			variadicArgs = args[3].([]transport.SubscribeHandlerOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Conn_SubscribeHandler_Call) Return(unsubscriber peanats.Unsubscriber, err error) *Conn_SubscribeHandler_Call {
	_c.Call.Return(unsubscriber, err)
	return _c
}

func (_c *Conn_SubscribeHandler_Call) RunAndReturn(run func(ctx context.Context, subj string, handler peanats.MsgHandler, opts ...transport.SubscribeHandlerOption) (peanats.Unsubscriber, error)) *Conn_SubscribeHandler_Call {
	_c.Call.Return(run)
	return _c
}
